name: GlobeEssentials
version: '1'
main: net.globemc.multicody10.globeessentials.Main
api-version: '1.21'
authors: [ Multicody10, VRILGQD ]
description: Various essential functions for GlobeMC
website: https://www.globemc.net
folia-supported: true
softdepend: [Towny]
commands:
  chatfilter:
    description: ChatFilter info
    default: true
    usage: "/chatfilter"
    aliases: [cf, chat, filter]
  coordinate:
    description: Converts real life coordinates to in-game coordinates.
    usage: "Usage: /<command>"
    permission: globeessentials.coordinate
    permission-message: You do not have permission to use this command.
  map:
    description: Sends the player a link to the map
    usage: "Usage: /<command>"
    permission: globeessentials.map
    permission-message: You do not have permission to use this command.
  help:
    description: Sends the player a link to the help page
    usage: "Usage: /<command>"
    permission: globeessentials.help
    permission-message: You do not have permission to use this command.
  recipes:
    description: Sends the player a link to the recipes page
    usage: "Usage: /<command>"
    permission: globeessentials.recipes
    permission-message: You do not have permission to use this command.
permissions:
  globeessentials.reload:
    default: op
    description: Reload plugin
  globeessentials.stafffilter:
    default: op
    description: Staff messages in ChatFilter
  globeessentials.bypass:
    default: false
    description: Bypass filter